on:
  # Run on release creation
    release:
        types: [published]

name: Publish package to PyPI

concurrency:
  group: ${{ github.workflow }}


jobs:
  # Publish to PyPI using uv build and uv publish on Python 3.10
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install uv
        run: |
          python -m pip install --upgrade uv

      - name: Build and publish package
        run: |
          uv build --no-dev
          uv publish --token ${{ secrets.PYPI_TOKEN }}
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}

