on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

name: Code quality checks

concurrency:
  group: ${{ github.workflow }}

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.7.4"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked --dev

      - name: Lint with ruff
        run: uv run ruff check --select I
    
      - name: Run type checking
        run: uv run mypy .

      - name: Run tests
        run: uv run pytest tests --vcr-record=none
